/**
 * Disclosure marker for seeded content.
 *
 * Demo arenas and bot accounts exist so a new platform does not look
 * abandoned, but visitors are about to spend real money — so anything not
 * generated by a real person says so. Subtle, never hidden.
 */
export function DemoDot({ className = "" }: { className?: string }) {
  return (
    <span
      title="Demo account: seeded content, not a real supporter"
      aria-label="Demo account"
      className={`inline-block w-1.5 h-1.5 rounded-full bg-primary shrink-0 ring-2 ring-primary/25 ${className}`}
    />
  );
}
